title: Bacillus Bulgaricus' Blog
author: BacillusBulgaricus
email: bacillus.bulgaricus@github.io
description: > # this means to ignore newlines until "baseurl:"
  Here I will be learning to create a simple blog site with the help of the GitHub learning bot and Jekyll.

# social links
twitter_username: BacillusBulgaricus
github_username:  BacillusBulgaricus

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
